### ISSUE TITLE
getting http 500 error and i think i'm not doing something right

### ISSUE THREAD

**Issue by bamboo2341** [NethercraftMC5608/NetherWorkshopDownloader#12]
the title already explains all the context that is necessary for this

I'm basically getting this type of error every time I try to download a terraria mod, now I just don't know if this has something to do with the id, tried the method of putting the page link but without result, so had to use the numbers of the workshop I wanted to download, at this point have no idea if i did a stupid move or they secretly put some kind of block that doesn't allow programs other than steam itself to download it (depending on them this is quite capable of be created) but this second assumption is not valid for this :/

**Comment by NethercraftMC5608** [comment]
Issue should now be resolved.
