### ISSUE TITLE
Downloaded files are corrupt.

### ISSUE THREAD

**Issue by aL1NaZ4R** [NethercraftMC5608/NetherWorkshopDownloader#14]
**Describe the bug**
downloaded files are corrupted + error in cmd

**Expected behavior**
to download the file correctly?

**Screenshots**
![image](https://user-images.githubusercontent.com/89677246/223999945-cfe04738-23e8-4171-a9d3-61da24d78109.png)
![image](https://user-images.githubusercontent.com/89677246/224000061-73c0da64-4364-45be-865e-2a83e2b1b649.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro
 - Browser: Microsoft Edge
 - Version: 10.0.19043 Build 19043

**Smartphone (please complete the following information):**
 - Device: SM-A305F/DS
 - OS: LineageOS 12
 - Browser Edge
 - Version: wtf xd

**Comment by exeScripter** [comment]
I have literally the same error as you.

**Comment by NethercraftMC5608** [comment]
It was a API problem, should now be fixed.
