### ISSUE TITLE
Failing to connect to API

### ISSUE THREAD

**Issue by Pdrewicz** [NethercraftMC5608/NetherWorkshopDownloader#15]
**Describe the bug**
Faills to connect to API.

**To Reproduce**
Shows immediately after opening on 2 latest releases.

**Expected behavior**
Connects to API.

**Screenshots**
![image](https://user-images.githubusercontent.com/106173218/227230570-fa0e45b2-3ed1-406b-9654-be3f9bc07fc9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H2

**Comment by NethercraftMC5608** [comment]
Happens from time to time, The API usually comes back online in a hour or a day, so just wait.
