### ISSUE TITLE
Couldn't find specified path

### ISSUE THREAD

**Issue by Pdrewicz** [NethercraftMC5608/NetherWorkshopDownloader#17]
I tried to download mods for rimworld (is on supported list) and got this error on every one:  
![image](https://user-images.githubusercontent.com/106173218/234958470-ff2d6808-1d57-4703-8a8b-e41a9fb1b3af.png)

Than I tried downloading mods for random games to see if it's a rimworld problem and got this every time:
![image](https://user-images.githubusercontent.com/106173218/234959212-ec1aaa55-2574-44a4-830e-66e4faae90e1.png)
Those files are in downloader folder, it's just not moving them. Unfortunately the rimworld ones aren't.

I downloaded mods for rimworld with your tool a long time ago and it worked.
Windows 10 21H2
NetherWorkshopDownloader 2 Legacy (latest)

BTW I also tried to download v3 but couldn't find it anywhere on both github and discord.

**Comment by NethercraftMC5608** [comment]
There is a thread in the discord server #"Fix for File not found error for NetherWorkshopDownloader2 Legacy" that should address this issue.
