### ISSUE TITLE
Error when opening

### ISSUE THREAD

**Issue by aL1NaZ4R** [NethercraftMC5608/NetherWorkshopDownloader#20]
I Opened the nether workshop downloader and it returned this error:
 ![image](https://github.com/NethercraftMC5608/NetherWorkshopDownloader/assets/89677246/a3686ad5-989a-40cf-8ed5-216c04e69865)

**Comment by NethercraftMC5608** [comment]
i have changed the executable, try downloading it again.

**Comment by RealDevMrz** [comment]
same problem
![image](https://github.com/NethercraftMC5608/NetherWorkshopDownloader/assets/80907454/f3f692e2-0ec2-4cc2-8d12-ae41d58d04d9)
