### ISSUE TITLE
Downloader not downloading workshop mods

### ISSUE THREAD

**Issue by CheeseburgerMuncher** [NethercraftMC5608/NetherWorkshopDownloader#22]
I open the downloader, which opens up normally and then whenever I try downloading a workshop mod this pops up and the downloader does nothing.
![image](https://github.com/NethercraftMC5608/NetherWorkshopDownloader/assets/144798776/3945926c-bd22-47c3-85c9-b1eb9bb4658f)
Would appreciate a response, thank you kindly.

**Comment by NethercraftMC5608** [comment]
I was updating it, it should work now.

**Comment by CheeseburgerMuncher** [comment]
Understood, thank you!
