### ISSUE TITLE
unable to download some specific mods

### ISSUE THREAD

**Issue by Edcaaaa4gy53** [NethercraftMC5608/NetherWorkshopDownloader#25]
**Describe the bug**
Some mods can't be downloaded

**To Reproduce**
Start it up
try to download something like: " https://steamcommunity.com/sharedfiles/filedetails/?id=3263415185 "
thats it

**Expected behavior**
mod getting downloaded

**Screenshots**
![Screenshot 2024-06-09 200205](https://github.com/NethercraftMC5608/NetherWorkshopDownloader/assets/100960013/1a34e259-683a-48ab-89fe-d8046943d7c0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: nether downloaded from Microsoft edge
 - Version: latest
**Additional context**
fix it... fast

**Comment by NethercraftMC5608** [comment]
Hey, I'm rewriting everything right now; you can be notified when it's back online via my Discord.
