### ISSUE TITLE
Can't download xcom 2 mods

### ISSUE THREAD

**Issue by Crysis123467** [NethercraftMC5608/NetherWorkshopDownloader#26]
i can't download any xcom 2 mods, i'm getting this error, i can't find the downloaded file.
![Screenshot 2024-06-24 133818](https://github.com/NethercraftMC5608/NetherWorkshopDownloader/assets/128551109/22199080-542c-4997-add7-41a21bb7763a)

**Comment by NethercraftMC5608** [comment]
Hopefully you have solved it already. 
Issue is shown on the alpha page 
https://github.com/NethercraftMC5608/NetherWorkshopDownloader/wiki/NetherWorkshopDownloader-Dameon-4-Alpha
