### ISSUE TITLE
Possible reasons for a timeout error?

### ISSUE THREAD

**Issue by SiN-Kiliko** [NethercraftMC5608/NetherWorkshopDownloader#3]
Vibing, attempting to install an addon. Wait about 10 seconds as it says downloading...
Timeout error.
Program crashes within a second. I didn't even notice the error the first time.
here's a screenshot

![image](https://user-images.githubusercontent.com/77063165/192134337-22923d09-1a2d-4c90-95b4-d716d86e0621.png)

Could be a variety of things, but I'd appreciate some things to try.

**Comment by SiN-Kiliko** [comment]
Upon further testing, other gmod addons download fine.
When I worm my way into the workshop content folders and use the GMAD Extractor, it turns out that this addon is a.... bin.. file? rather than a .gma?
Must be the reason. Strange, and I wouldn't know how to open it.

**Comment by NethercraftMC5608** [comment]
Hey, can you provide the workshop ids that is causing this?
Thanks.

**Comment by SiN-Kiliko** [comment]
Thank you!
