### ISSUE TITLE
I don't know where the mods are being instaled

### ISSUE THREAD

**Issue by amunategui2005** [NethercraftMC5608/NetherWorkshopDownloader#4]
I choose a mod and downloaded in diferent folders but there is no mod, is because I need to download it in a specific folder?

**Comment by NethercraftMC5608** [comment]
Hey, what game are you trying to download mods for?
And also please send a screenshot if you can.

**Comment by NethercraftMC5608** [comment]
Closing issue as no response in 4 days.
Typically the issue is that the game is not supported, or you are having a timeout error (which usually occurs when you use a old mod that has not been updated or indexed), you can use steamweb api to download the old mod.
