### ISSUE TITLE
14 different antivirus found the exe as a trojan horse

### ISSUE THREAD

**Issue by 0xEnjoy** [NethercraftMC5608/NetherWorkshopDownloader#5]
**Describe the bug**

The exe inside the zip file is being detected as a virus by 14 different anti viruses describing it as a trojan horse.
https://www.virustotal.com/gui/file/3f701834673e22b87ac5aade1f95f5df2ac84e3c68e202c2297545e9da8fe565

**To Reproduce**

1. Go to virus total or your anti virus
2. Scan the exe
3. It is detected as a virus

**Expected behavior**
Not to be called a trojan horse by almost all mainstream anti viruses?

**Screenshots**

![image](https://user-images.githubusercontent.com/104784056/192794556-b04b18cf-db49-4a1a-be83-96dbceea0d7f.png)

**Desktop (please complete the following information):**
 - OS: Windows 8.1  
 - Version 2  

**Additional context**
Could you like fix this?

**Comment by NethercraftMC5608** [comment]
This application uses powershell with administrator privileges, also uses python. This can imitate as a virus to antiviruses. 
**If you do not want to run the executable but still run the program. View the source code below and use python to create your own exe.**
https://pastebin.com/jDT9Mn3m
Password: wxngJgAaEp

**Comment by NethercraftMC5608** [comment]
Just created a new version [V1.1b](https://github.com/NethercraftMC5608/NetherWorkshopDownloader/releases/tag/V1.1B)
**that does not use powershell and administrator privileges anymore. and is 5 vendors safer when doing a virus total scan.**
![image](https://user-images.githubusercontent.com/89841173/192944842-4c980252-30aa-4c93-ab12-2ce424fe20d3.png)

**Comment by NethercraftMC5608** [comment]
> I put the new exe of the version 1.0B and it still says it is trojan horse. Please fix it you did not fix it

I can't fix that. It's not my website and it's falsely reported, If a trojan was in NetherWorkshopDownloader2 people will already know by now. Use your actual antivirus software to check for malware. Virus total checks the reliablity of the source, Even with unsigned/built official app's like discord, teamspeak virus total still falsely reports.
[If you don't trust the source, you can always make your own.](https://github.com/NethercraftMC5608/NetherWorkshopDownloader/wiki/NetherWorkshopDownloader2-Indepth)
