### ISSUE TITLE
Program claims a mod was successfully downloaded when it wasn't

### ISSUE THREAD

**Issue by Queenofdragons6** [NethercraftMC5608/NetherWorkshopDownloader#7]
As the title says, I decided to test the program by trying to download a mod for a game that doesn't allow anonymous (or even non-anonymous) third-party downloads, and the program claimed that the mod was downloaded to the selected folder even though there was nothing there.

**Comment by NethercraftMC5608** [comment]
What game are you trying to download a mod with?

**Comment by Queenofdragons6** [comment]
Starbound. (Didn't work with any other workshop downloader, so I didn't expect it to work here. Just wanted to test it and see what would happen.)

**Comment by NethercraftMC5608** [comment]
Yeah, unfortunately we dont support starbound. You can check the API supported games [here.](https://github.com/NethercraftMC5608/NetherWorkshopDownloader/wiki/Supported-API-games)

**Comment by Queenofdragons6** [comment]
I know it's not supported. My issue was that the program falsely claimed the mod download was successful.

**Comment by Queenofdragons6** [comment]
It should not be saying this, should it?
![false success](https://user-images.githubusercontent.com/99419004/195011476-936e0aee-201e-478d-9f2b-3d84ed500da0.PNG)
