### ISSUE TITLE
Program falsely claims mod download was successful

### ISSUE THREAD

**Issue by Queenofdragons6** [NethercraftMC5608/NetherWorkshopDownloader#8]
![false success](https://user-images.githubusercontent.com/99419004/195015347-a09fad71-eb38-450b-9aa8-9a75ab777ad7.PNG)
![empty](https://user-images.githubusercontent.com/99419004/195014246-4909ec6b-8ea0-40b0-acd1-da1d60aabf02.PNG)
It should not be saying this.
What mod it was trying to download or what game the mod is for isn't relevant, the issue is that _the program is wrong about the download being successful_ and does not seem to be able to say that the download failed.
It's not gonna be good for people to wrongly think the downloader can do something it can't.

**Comment by NethercraftMC5608** [comment]
**Yes this is a issue, and can be fixed.**
Thanks.
I am working on a fix for this in the next later versions.

**Comment by NethercraftMC5608** [comment]
**[New version should fix this issue.](https://github.com/NethercraftMC5608/NetherWorkshopDownloader/releases/tag/V2.1A)**
